version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "6500:5432"
    restart: always
    env_file:
      - ./.env
    # volumes:
    #   - postgres-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    restart: always
# volumes:
# postgres-db:
